### ISSUE TITLE
API erros on Settings Preview

### ISSUE THREAD

**Issue by jonyroda97** [cyyynthia/better-replies#4]
After a lot of time trying to load, it gives the error below.

![image](https://user-images.githubusercontent.com/8282833/113494626-d1012e00-94e1-11eb-92c5-837523cd8587.png)
![image](https://user-images.githubusercontent.com/8282833/113494631-e413fe00-94e1-11eb-9f81-64a913367d4a.png)

**Comment by cyyynthia** [comment]
This is a problem with Rich Quotes, not from my plugin
